version: "3"

server:
  command: "php public/index.php"
  env:
    - APP_RUNTIME: Baldinof\RoadRunnerBundle\Runtime\Runtime

# http:
#   address: 0.0.0.0:80
#   pool:
#     num_workers: 10
#     allocate_timeout: 30s
#     reset_timeout: 30s
#     stream_timeout: 30s
#     destroy_timeout: 30s
#     debug: false
#     supervisor:
#       idle_ttl: 30s
#       exec_ttl: 30s

#   middleware: [ "static", "gzip" ]
#   uploads:
#     forbid: [ ".php", ".exe", ".bat" ]
#   static:
#     dir: "public"
#     forbid: [ ".php", ".htaccess" ]

logs:
  mode: production
  channels:
    http:
      level: debug
    server:
      level: info
      mode: raw
    metrics:
      level: error

rpc:
  listen: tcp://127.0.0.1:6001

status:
  address: 127.0.0.1:2114

metrics:
  address: 0.0.0.0:2112

