controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

dictionary:
    path: /dictionary              
    controller: App\Controller\DictionaryController::index
    methods: GET
